export enum Family {
  BOIS,
  CUIVRES,
  PERCUSSIONS,
  CORDES
}

export enum SubFamily {
  BOIS_BISEAU,
  BOIS_ANCHE_DOUBLE,
  BOIS_ANCHE_SIMPLE,
  PERCUSSIONS_NON_DETERMINE,
  PERCUSSIONS_DETERMINE,
  CORDES_FROTTEES,
  CORDES_PINCEES_DOIGTS,
  CORDES_PINCEES_CLAVIER,
  CORDES_FRAPPEES
}
